config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'pages#home'
  resources :restaurants do
    resources :bookings, only: [:new, :create, :edit, :update, :destroy]
    resources :reviews, only: [:create, :new]
  end
  get '/my-bookings', to: "dashboard#my_bookings"
  get '/my-restaurants', to: "dashboard#my_restaurants"
  get '/booking-requests', to: "dashboard#booking_requests"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :restaurant
  
  validates :number_of_people, presence: true
  validates :start_date, presence: true
  validates :end_date, presence: true
  validate  :dates
  # validates :end_date, presence: true, end_date: { after_or_equal_to:  :start_date}

  def dates
    if start_date < Date.today
      errors.add(:start_date, "can't be in the past")
    elsif end_date < start_date
      errors.add(:end_date, "cannot be before start date")
    end
  end

  def total_price
    number_of_days = self.end_date - self.start_date
    n = number_of_days.to_i
   total_price = self.restaurant.price *  self.number_of_people * n
  end
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  belongs_to :user
  has_many :bookings
  has_many :reviews
  mount_uploader :photo, PhotoUploader
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  validates :name, presence: true

  validates :price, presence: true

  include PgSearch
  pg_search_scope :search_by_name_and_category,
    against: [ :name, :category],
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :bookings
  has_many :restaurants

 def reservations
  restaurants.map { |restaurant| restaurant.bookings }.flatten
 end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  include Pundit

  # Pundit: white-list approach.
  # only asks for authorization unless devise controller, admin, index, my_rest, my_books
  after_action :verify_authorized, except: [:index, :my_restaurants, :my_bookings], unless: :skip_pundit?
  after_action :verify_policy_scoped, only: [:index, :my_restaurants, :my_bookings], unless: :skip_pundit?
  before_action :configure_permitted_parameters, if: :devise_controller?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end


  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

  private

  def skip_pundit?
    # checks if it's a devise controller or an admin
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  before_action :find_booking, only: [:edit, :update, :destroy]

  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @booking = Booking.new
    authorize @booking
  end

  def create
    @booking = Booking.new(booking_params)
    @restaurant = Restaurant.find(params[:restaurant_id])
    @booking.restaurant = @restaurant
    authorize @booking
    @booking.user = current_user
    if @booking.save
      redirect_to my_bookings_path
    else
      render :new
    end
  end

  def edit
    authorize @booking
  end

  def update
    restaurant = Restaurant.find(params[:restaurant_id])
    @booking.update(booking_params)
    authorize @booking
    if @booking.save
      redirect_to booking_requests_path
    else
      render :edit
    end
  end

  def destroy
    restaurant = Restaurant.find(params[:restaurant_id])
    authorize @booking
    @booking.destroy
    # if it cannont redirect back, it goes to root_path
    redirect_back(fallback_location: root_path)
  end



private

  def booking_params
    params.require(:booking).permit(:number_of_people, :start_date, :end_date, :restaurant_id, :user_id, :status)
  end

  def find_booking
    @booking = Booking.find(params[:id])
  end

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  skip_after_action :verify_authorized

  def my_bookings
    @bookings = policy_scope(Booking).where(user: current_user)
  end

  def my_restaurants
    # policy_scope calls solve method that retrieves all restaurants
    @restaurants = policy_scope(Restaurant).where(user: current_user)
  end

  def booking_requests
    @reservations = current_user.reservations
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!

  def home
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  before_action :find_rest, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: [:index, :show]
  def new
    @restaurant = Restaurant.new
    # calls for the same method within restaurant_policy
    authorize @restaurant
  end

  def index
    # policy_scope is a method that calls the scope resolve from REst_policy
    if params[:query].present?
      sql_query = "name ILIKE :query OR category ILIKE :query"
      @restaurants = policy_scope(Restaurant).where(sql_query, query: "%#{params[:query]}%").order(created_at: :desc)
      @restaurants = @restaurants.where.not(latitude: nil, longitude: nil)
      @markers = @restaurants.map do |restaurant|
      {
        lat: restaurant.latitude,
        lng: restaurant.longitude#,
        # infoWindow: { content: render_to_string(partial: "/restaurants/map_box", locals: { restaurant: restaurant }) }
      }
      end
    else
      @restaurants = policy_scope(Restaurant).order(created_at: :desc)
      @restaurants = @restaurants.where.not(latitude: nil, longitude: nil)
      @markers = @restaurants.map do |restaurant|
      {
        lat: restaurant.latitude,
        lng: restaurant.longitude#,
        # infoWindow: { content: render_to_string(partial: "/restaurants/map_box", locals: { restaurant: restaurant }) }
      }
      end
    end
  end

  def show
    # calls for the same method within restaurant_policy
    authorize @restaurant
    @markers = [{lat: @restaurant.latitude, lng: @restaurant.longitude}]
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.user = current_user
    # calls for the same method within restaurant_policy
    authorize @restaurant
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  def edit
    authorize @restaurant
  end

  def update
    authorize @restaurant
    @restaurant.update(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :edit
    end
  end

  def destroy
    authorize @restaurant
    @restaurant.destroy
    redirect_to restaurants_path
  end


  private

  def find_rest
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :user_id, :photo, :address, :price, :category, :description)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_restaurant

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    if @review.save
      @review_count = @restaurant.reviews.size

        redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end


  private

  def review_params
    params.require(:review).permit(:content, :stars)
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_form.html.erb
<div class="form-group">
  <%= simple_form_for [@restaurant, @booking] do |f| %>
    <% if @booking.errors.any? %>
      <div class="errors-container">
        <ul>
          <% @booking.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <%= f.input :number_of_people %>
    <%= f.date_field :start_date %>
    <%= f.date_field :end_date %>
    <div class="text-center"> <%= f.button :submit, class: 'btn btn-blue' %> </div>
  <% end %>
</div>

app/views/bookings/new.html.erb
<div class="bannernew" style="background-image: linear-gradient(-225deg, rgba(0,0,0,0.4) 0%, rgba(0,0,0,0.4) 50%), url('<%= image_path 'rob-bye-141857-unsplash.jpg' %>');">
  <h1 class="text-center">Book this restaurant</h1>

      <div class="container-form">
      <%= render 'form', booking: @booking %>
      </div>
</div>

app/views/dashboard/_form.html.erb
<%= simple_form_for [booking.restaurant, booking] do |f| %>
  <% if booking.errors.any? %>
    <div class="errors-container">
      <ul>
        <% booking.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.input :status, collection: ["pending", "accepted", "declined"] %>
  <%= f.submit "Update", class: "btn btn-blue" %>
<% end %>

app/views/dashboard/booking_requests.html.erb
<div class="container">
  <h2 class="text-center">My booking requests</h2>
  <% @reservations.each do |request| %>
    <div class="message">
      <img class="avatar-small" src="https://kitt.lewagon.com/placeholder/users/gabriel-dehan">
      <div class="message-name">
        <h3> <%=  request.user.name %></h3>
        <p> <%= request.number_of_people %> people </p>
      </div>
      <div class="message-body">
        <p><strong> <%=  request.restaurant.name %></strong></p>
        <p>
         From  <%= request.start_date %> to <%= request.end_date %>
        </p>
      </div>
        <p class="price"> <%= request.total_price %> € </p>
      <div class="message-status text-center">
        <div class="form-group">
          <%= render 'form', booking: request %>
        </div>
      </div>
      <div>
        <%= link_to ('<i class="fa fa-trash"></i>').html_safe, restaurant_booking_path(request.restaurant, request), method: :delete, data: { confirm: "Are you sure?"}, class: 'btn btn-blue'%>
      </div>
    </div>
  <% end %>
</div>

<!-- #f5f5f5 -->

app/views/dashboard/my_bookings.html.erb
<div class="container">
  <h2 class="text-center">My bookings</h2>
  <% @bookings.each do |booking| %>
    <div class="message">
      <img class="avatar-small" src="https://kitt.lewagon.com/placeholder/users/gabriel-dehan">
      <div class="message-name">
      <p> <%= booking.number_of_people %> people </p>
    </div>
    <div class="message-body">
      <p><strong> <%=  booking.restaurant.name %></strong></p>
      <p>
       From  <%= booking.start_date %> to <%= booking.end_date %>
      </p>
    </div>
    <div class="message-status message-status--<%= booking.status %> text-center">
        <%= booking.status %>
        <p class="price"> <%= booking.total_price %> € </p>
    </div>
    <div>
      <%= link_to ('<i class="fa fa-trash"></i>').html_safe, restaurant_booking_path(booking.restaurant, booking), method: :delete, data: { confirm: "Are you sure?" }, class: 'btn btn-blue'%>
    </div>
  </div>
<% end %>

</div>

app/views/dashboard/my_restaurants.html.erb
<div class="container">
  <h2 class="text-center">My restaurants </h2>
  <% @restaurants.each do |restaurant| %>
    <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= restaurant.photo_url %>');">
      <div class="card-title-wrapper">
        <h2> <%= restaurant.name.upcase %> </h2>
      </div>

      <div class="card-edit-wrapper">
        <%= link_to '<i class="fas fa-pen-square"></i>'.html_safe, edit_restaurant_path(restaurant) %>
      </div>

      <div class="card-category"> <%= restaurant.category.capitalize %>
      </div>
      <div class="card-description">
        <p> <i class="fas fa-euro-sign"></i> <%= restaurant.price %> /day /pers </p>
        <p>  <i class="fas fa-map-marker"></i> <%= restaurant.address %> </p>
      </div>
    </div>
  <% end %>
  <p class="text-center"> <%= link_to "Add a new restaurant", new_restaurant_path, class: "btn btn-blue" %> </p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>EasyFork</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render "components/navbar" %>
    <%= yield %>
    <%= render "components/footer" %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
    <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?libraries=places&key=#{ENV['GOOGLE_API_BROWSER_KEY']}" %>
    <%= javascript_pack_tag "map" %>
  </body>
</html>

app/views/pages/_form.html.erb
<div class="container-search">

  <%= form_tag restaurants_path, method: :get do %>
  <%= text_field_tag :query,
    params[:query],
    class: "form-control",
    placeholder: " Find a restaurant or category"
  %>
  <% end %>

</div>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,0,0,0.5) 0%, rgba(0,0,0,0.5) 50%), url('<%= image_path 'laurent-perren-477138-unsplash (1).jpg' %>');">
  <div class="banner-content">
    <link href="https://fonts.googleapis.com/css?family=Source+Code+Pro:200" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Work+Sans:100" rel="stylesheet">
    <main>
        <h1 class="e">E</h1>
        <h1 class="a">a</h1>
        <h1 class="s">s</h1>
        <h1 class="y">y</h1>
        <h1 class="f">F</h1>
        <h1 class="o">o</h1>
        <h1 class="r">r</h1>
        <h1 class="k">k</h1>
    </main>
    <h2>Ever booked a restaurant for a few days? Me neither! 🤪</h2>


      <%= render 'form' %>

    <br>
    <%= link_to "See all Restaurants", restaurants_path, class: "btn btn-blue" %>
  </div>
</div>

app/views/restaurants/_form.html.erb
<div class="container-form">
  <%= simple_form_for [restaurant] do |f| %>
    <% if @restaurant.errors.any? %>
      <div class="errors-container">
        <ul>
          <% @restaurant.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <%= f.input :name %>

    <%= f.input :category %>

    <%= f.input :address %>
    <%= f.input :price %>
    <%= f.input :description %>
    <%= f.input :photo %>
    <%= f.input :photo_cache, as: :hidden %>
    <div class="text-center"> <%= f.button :submit, class: 'btn btn-blue' %> </div>
  <% end %>
</div>

app/views/restaurants/edit.html.erb
<div class="bannernew" style="background-image: linear-gradient(-225deg, rgba(0,0,0,0.4) 0%, rgba(0,0,0,0.4) 50%), url('<%= image_path 'jay-wennington-2065-unsplash.jpg' %>');">
  <h1 class="text-center"> <%= @restaurant.name %> <%= link_to '<i class="fas fa-trash-alt"></i>'.html_safe, restaurant_path(@restaurant), method: :delete, data: { confirm: "Are you sure?" }, class: 'btn btn-blue'%> </h1>
  <div class="form-group">
    <%= render "form", restaurant: @restaurant %>
  </div>
</div>
<div class="text-center"> <%= link_to "Back to the restaurant", restaurant_path, class: "btn btn-blue" %> </div>

app/views/restaurants/index.html.erb
<div class="container">
  <% if current_user != nil %>
    <h2 class="text-center"> We found <%= @restaurants.count %> restaurants for you, <%= current_user.name %>. </h2>
  <% else %>
    <h2 class="text-center"> We found <%= @restaurants.count %> restaurants for you. </h2>
  <% end %>
  <%= render :partial => 'pages/form' %>
  <br>
</div>

<div class="main-container">

  <div class="card-container">
    <div class="row">
      <% @restaurants.each do |restaurant| %>
        <div class="col-xs-12 col-md-6">
          <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.5), rgba(0,0,0,0.5)), url('<%= restaurant.photo_url %>');">
            <div class="card-title-wrapper">
              <h2> <%= restaurant.name.upcase %></h2>
            </div>
          <div class="card-category"> <%= restaurant.category.capitalize %></div>
          <div class="card-description">
            <p> <i class="fas fa-euro-sign"></i> <%= restaurant.price %> /day /pers</p>
            <p><i class="fas fa-map-marker"></i> <%= restaurant.address %> </p>
          </div>
          <%= link_to "", restaurant_path(restaurant), class: "card-link" %>
        </div>
      </div>
      <% end %>
    </div>
  </div>

  <br>

  <div class="map-container">
    <div
      id="map"
      style="width: 100%;
      height: 500px;"
      data-markers="<%= @markers.to_json %>"
      >
    </div>
  </div>

</div>

<div class="banner banner-show-rest">
  <%= link_to "Add a new restaurant", new_restaurant_path, class: "btn btn-blue" %>
</div>

app/views/restaurants/new.html.erb
<div class="bannernew" style="background-image: linear-gradient(-225deg, rgba(0,0,0,0.3) 0%, rgba(0,0,0,0.3) 50%), url('<%= image_path 'jay-wennington-2065-unsplash.jpg' %>');">
 <h1 class="text-center">Create a new restaurant</h1>


 <%= render 'form', restaurant: @restaurant %>

</div>

app/views/restaurants/show.html.erb
 <link href="https://fonts.googleapis.com/css?family=Amaranth|Armata|Krona+One" rel="stylesheet">
<div class="map" style="background-image: url('<%= @restaurant.photo_url %>')"></div>
  <div class="container margin-top-negative">

    <% if @current_user == nil %>


      <div class="row" >

         <div style="width: 60%; float:left">
            <div class="restaurant-show-title">
              <h1><%= @restaurant.name %></h1>
              <p class="restaurant-show-address"><%= @restaurant.address %></p>
              <div class="restaurant-show-address">
                <h4><%= @restaurant.description  %></h4>
              </div>
                <p> <%= link_to "Book Now",  new_restaurant_booking_path(@restaurant), class: "btn btn-cute" %> </p>
            </div>
          </div>

          <div style="width: 38%; float:right">

              <div class="restaurant-show-card">
                  <h3>Details</h3>
                  <div class="flex">
                    <div class="flex ml-3">
                      <i class="material-icons mr-2">Price: <%= @restaurant.price %> €</i>
                    </div>
                  </div>
                </div>

          </div>

            <div style="width: 38%; float:right">

             <div class="restaurant-show-category">
                <h3>Category</h3>
                <i> <%= @restaurant.category %> </i>
             </div>

            </div>

    <!-- Row -->
    </div>

          <div class="map">
            <div
              id="map"
              style="width: 100%;
              height: 380px;"
              data-markers="<%= @markers.to_json %>"
            ></div>
          </div>



    <% else %>



      <div class="row" >

         <div style="width: 60%; float:left">
            <div class="restaurant-show-title">
              <h1><%= @restaurant.name %></h1>
              <p class="restaurant-show-address"><%= @restaurant.address %></p>
              <div class="restaurant-show-address">
                <h4><%= @restaurant.description  %></h4>
              </div>
              <% if @restaurant.user_id != @current_user.id %>
                <div class="button-book">
                 <%= link_to "Book Now",  new_restaurant_booking_path(@restaurant), class: "btn btn-cute" %>
                 </div>
              <% end %>
              <% if @restaurant.user_id == @current_user.id  %>
              <div class="button-edit">
               <p>Edit your restaurant <%= link_to '<i class="fas fa-edit"></i>'.html_safe, edit_restaurant_path %></p>
               </div>
              <% end %>

            </div>
          </div>

          <div style="width: 38%; float:right">

              <div class="restaurant-show-card">
                  <h3>Details</h3>
                  <div class="flex">
                    <div class="flex ml-3">
                      <i class="material-icons mr-2">Price: <%= @restaurant.price %> €</i>
                    </div>
                  </div>
                </div>

          </div>

            <div style="width: 38%; float:right">

             <div class="restaurant-show-category">
                <h3>Category</h3>
                <i> <%= @restaurant.category %> </i>
             </div>

            </div>

    <!-- Row -->
    </div>

          <div class="map">
            <div
              id="map"
              style="width: 100%;
              height: 380px;"
              data-markers="<%= @markers.to_json %>"
            ></div>
          </div>




    <% end %>
  </div>
</div>

app/views/reviews/_form.html.erb
<%= simple_form_for([restaurant, review], remote: true) do |f| %>
  <%= f.input :content %>
  <%= f.input :stars %>
  <%= f.submit %>
<% end %>

app/views/reviews/new.html.erb
<%= render 'form', restaurant: @restaurant, review: @review %>